.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GDDCCONTROL 1 "July 26, 2006"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
gddccontrol \- A graphical utility to control monitor parameters via software
.SH SYNOPSIS
.B gddccontrol
.RI [options]
.SH DESCRIPTION
This manual page documents briefly the
.B gddccontrol
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBgddccontrol\fP is an open source utility which allows controlling monitor parameters via software.
.SH OPTIONS
As a GTK2 application, \fBgddccontrol\fP accepts the standard GTK2 options.
.SH SEE ALSO
The program is documented fully in
.br
/usr/share/doc/ddccontrol/html/index.html
.PP
The project homepage: http://ddccontrol.sourceforge.net
.SH AUTHOR
ddccontrol was written by Oleg I. Vdovikin and Nicolas Boichat.
.br
Copyright 2004\-2005 Oleg I. Vdovikin (oleg@cs.msu.su)
.br
Copyright 2004\-2006 Nicolas Boichat (nicolas@boichat.ch)
.PP
This manual page was written by Roberto C. Sanchez <roberto@familiasanchez.net>.

