//Dummy header file used for translation generation...
#define DUMMY {
printf(_("Color settings"));
printf(_("Brightness and Contrast"));
printf(_("Brightness"));
printf(_("Contrast"));
printf(_("Magic Bright Mode"));
printf(_("Text"));
printf(_("Internet"));
printf(_("Entertain"));
printf(_("Custom"));
printf(_("Color maximum level"));
printf(_("Red maximum level"));
printf(_("Green maximum level"));
printf(_("Blue maximum level"));
printf(_("Color minimum level"));
printf(_("Red minimum level"));
printf(_("Green minimum level"));
printf(_("Blue minimum level"));
printf(_("Various color settings"));
printf(_("Hue"));
printf(_("Saturation"));
printf(_("Color curve adjust"));
printf(_("Color Preset"));
printf(_("Normal"));
printf(_("Warm"));
printf(_("Cool"));
printf(_("5000K"));
printf(_("6500K"));
printf(_("7500K"));
printf(_("8200K"));
printf(_("9300K"));
printf(_("Native"));
printf(_("Position and size"));
printf(_("Position"));
printf(_("Horizontal Position"));
printf(_("Vertical Position"));
printf(_("Size"));
printf(_("Horizontal Size"));
printf(_("Vertical Size"));
printf(_("Automatic adjustments"));
printf(_("Auto Size Center"));
printf(_("Enable"));
printf(_("Disable"));
printf(_("Automatically adjust Size and Position"));
printf(_("Geometry"));
printf(_("Pincushion"));
printf(_("Horizontal Pincushion"));
printf(_("Horizontal Pincushion Balance"));
printf(_("Vertical Pincushion"));
printf(_("Vertical Pincushion Balance"));
printf(_("Linearity"));
printf(_("Horizontal Linearity"));
printf(_("Horizontal Linearity Balance"));
printf(_("Vertical Linearity"));
printf(_("Vertical Linearity Balance"));
printf(_("Misconvergence"));
printf(_("Horizontal Misconvergence"));
printf(_("Vertical Misconvergence"));
printf(_("General distortion"));
printf(_("Parallelogram Distortion (Key Balance)"));
printf(_("Trapezoidal Distortion (Key)"));
printf(_("Corners distortion"));
printf(_("Top Corner Distortion Control"));
printf(_("Top Corner Distortion Balance"));
printf(_("Bottom Corner Distortion Control"));
printf(_("Bottom Corner Distortion Balance"));
printf(_("Rotation"));
printf(_("Rotation (Tilt)"));
printf(_("Screen purity"));
printf(_("Moire"));
printf(_("Horizontal Moire"));
printf(_("Vertical Moire"));
printf(_("Corners purity"));
printf(_("Top left screen purity"));
printf(_("Top right screen purity"));
printf(_("Bottom left screen purity"));
printf(_("Bottom right screen purity"));
printf(_("Various"));
printf(_("Focus"));
printf(_("Image Lock Coarse"));
printf(_("Image Lock Fine (Clock Phase)"));
printf(_("Landing Adjust (RGB alignment)"));
printf(_("Sharpness"));
printf(_("Others"));
printf(_("Restore defaults"));
printf(_("Restore Factory Defaults"));
printf(_("Restore Brightness and Contrast"));
printf(_("Restore Factory Default Geometry"));
printf(_("Restore Factory Default Color"));
printf(_("Restore Factory Default Position"));
printf(_("Restore Factory Default Size"));
printf(_("Settings"));
printf(_("Save Current Settings"));
printf(_("Restore Factory Settings"));
printf(_("Audio"));
printf(_("Audio Speaker Volume Adjust"));
printf(_("Audio Microphone Volume Adjust"));
printf(_("Degauss"));
printf(_("Degauss"));
printf(_("Secondary Degauss"));
printf(_("OSD"));
printf(_("On Screen Display"));
printf(_("Disable"));
printf(_("Enable"));
printf(_("Enable only brightness/contrast settings"));
printf(_("Language select"));
printf(_("English"));
printf(_("French"));
printf(_("German"));
printf(_("Italian"));
printf(_("Russian"));
printf(_("Spanish"));
printf(_("Swedish"));
printf(_("Chinese"));
printf(_("Input settings"));
printf(_("Input level Select"));
printf(_("Input Source Select"));
printf(_("Analog"));
printf(_("Digital"));
printf(_("Power control"));
printf(_("DPMS Control"));
printf(_("On"));
printf(_("Standby"));
printf(_("Power control"));
printf(_("Off"));
printf(_("On"));
}
