//! Build standalone monitor profiles using the installed database's vocabulary.
//!
//! An address or enum value missing from options.xml is deliberately not guessed:
//! capabilities report numeric support, not manufacturer-specific meanings.

use ddccontrol_caps::{Caps, MonitorType};
use roxmltree::{Document, Node};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Reading {
    pub current: u16,
    pub maximum: u16,
}

#[derive(Debug)]
pub struct Scan {
    pub pnp_id: String,
    pub name: String,
    pub caps: Caps,
    pub readings: BTreeMap<u8, Reading>,
}

#[derive(Debug, Eq, PartialEq)]
struct OptionControl {
    id: String,
    name: String,
    kind: String,
    values: Vec<(String, Option<u16>)>,
}

type Options = BTreeMap<u8, Vec<OptionControl>>;

/// Addresses worth querying when the monitor does not advertise capabilities.
pub fn candidate_codes(options_xml: &str) -> Result<Vec<u8>, String> {
    Ok(parse_options(options_xml)?.into_keys().collect())
}

/// Generate a UTF-8 XML profile accepted by ddccontrol's monitor database.
pub fn generate(scan: &Scan, options_xml: &str) -> Result<String, String> {
    let options = parse_options(options_xml)?;
    let codes: BTreeSet<u8> = scan
        .caps
        .vcp_codes()
        .chain(scan.readings.keys().copied())
        .collect();
    let mut xml = String::from("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    comment(
        &mut xml,
        "",
        &format!(
            "Generated by ddccontrol-scanmonitor for {}.\n\
             Save as {}.xml in the database's monitor directory.\n\
             The scan does not set control values; setting values has not been tested.\n\
             Active controls have readable, unambiguous database mappings.\n\
             Review and test them on the monitor before submitting this file.\n\
             To enable a candidate, verify its meaning and values, then remove\n\
             its surrounding XML comment. Keep only one control per address.\n\
             Change init to samsung only if the monitor requires Samsung initialization.",
            scan.pnp_id, scan.pnp_id
        ),
    );
    writeln!(
        xml,
        "<monitor name=\"{}\" init=\"standard\">",
        attribute(if scan.name.trim().is_empty() {
            &scan.pnp_id
        } else {
            &scan.name
        })
    )
    .unwrap();
    if !codes.is_empty() {
        // Keep readable controls available even if firmware omits them from caps.
        // Retaining the advertised codes also makes commented candidates editable.
        let caps = normalized_caps(scan, &codes);
        writeln!(xml, "\t<caps add=\"{}\"/>", attribute(&caps)).unwrap();
    }
    xml.push_str("\t<controls>\n");
    for code in codes {
        let reading = scan.readings.get(&code);
        let advertised = scan.caps.vcp(code).and_then(|vcp| vcp.values());
        let mut observation = format!("VCP 0x{code:02X}");
        match reading {
            Some(reading) => write!(
                observation,
                ": current={}, maximum={}",
                reading.current, reading.maximum
            )
            .unwrap(),
            None if code >= 0xe0 => observation.push_str(": advertised; vendor address not probed"),
            None => observation.push_str(": advertised, but no successful read"),
        }
        if let Some(values) = advertised {
            write!(observation, "; advertised values: {}", hex_values(values)).unwrap();
        }
        comment(&mut xml, "\t\t", &observation);
        let Some(candidates) = options.get(&code) else {
            comment(
                &mut xml,
                "\t\t",
                "Unknown control: options.xml has no address mapping.\n\
                 Identify its meaning and an existing option ID before adding a control.",
            );
            continue;
        };
        for candidate in candidates {
            let values = matching_values(candidate, advertised);
            let mut reasons = Vec::new();
            if reading.is_none() {
                reasons.push("no successful read");
            }
            if candidates.len() > 1 {
                reasons.push("several option IDs share this address; choose the verified one");
            }
            if options.iter().any(|(other_code, controls)| {
                *other_code != code && controls.iter().any(|control| control.id == candidate.id)
            }) {
                reasons
                    .push("this option ID has several possible addresses; choose the verified one");
            }
            if code >= 0xe0 {
                reasons.push("manufacturer-specific address; verify this mapping on the monitor");
            }
            if candidate.kind == "command" {
                reasons.push("commands require manual verification before enabling");
            }
            if candidate.kind == "value"
                && reading.is_some_and(|read| read.maximum == 0 || read.current > read.maximum)
            {
                reasons.push("the reported range does not establish an adjustable scalar");
            }
            if candidate.kind == "list" {
                if values.is_empty() {
                    reasons.push("no confirmed enum mappings; add verified value IDs and numbers");
                } else if ambiguous_values(&values) {
                    reasons.push("enum IDs or numbers have more than one possible meaning");
                }
            }
            let control = control_xml(candidate, code, &values);
            if reasons.is_empty() {
                comment(&mut xml, "\t\t", &candidate.name);
                xml.push_str(&control);
            } else {
                comment(
                    &mut xml,
                    "\t\t",
                    &format!(
                        "Candidate {} ({}): {}.",
                        candidate.id,
                        candidate.name,
                        reasons.join("; ")
                    ),
                );
                comment(&mut xml, "\t\t", &format!("\n{}\t\t", control));
            }
            if candidate.kind == "list" {
                enum_notes(&mut xml, candidate, advertised, &values);
            }
        }
    }
    xml.push_str("\t</controls>\n</monitor>\n");
    Ok(xml)
}

fn parse_options(xml: &str) -> Result<Options, String> {
    let doc = Document::parse(xml).map_err(|error| format!("Invalid options.xml: {error}"))?;
    let root = doc.root_element();
    if !root.has_tag_name("options") || root.attribute("dbversion") != Some("3") {
        return Err("options.xml must contain <options dbversion=\"3\">".to_string());
    }
    if root.attribute("date").is_none() {
        return Err("options.xml is missing its date attribute".to_string());
    }
    let mut result = Options::new();
    for group in root.children().filter(|node| node.has_tag_name("group")) {
        required(group, "name")?;
        for subgroup in group
            .children()
            .filter(|node| node.has_tag_name("subgroup"))
        {
            required(subgroup, "name")?;
            for control in subgroup
                .children()
                .filter(|node| node.has_tag_name("control"))
            {
                let id = required(control, "id")?.to_string();
                let name = required(control, "name")?.to_string();
                let kind = required(control, "type")?.to_string();
                if !matches!(kind.as_str(), "value" | "list" | "command") {
                    return Err(format!("Invalid control type in options.xml: {kind}"));
                }
                if !matches!(control.attribute("refresh"), None | Some("none" | "all")) {
                    return Err(format!("Invalid refresh type in options.xml for {id}"));
                }
                let mut values = Vec::new();
                for value in control.children().filter(|node| node.has_tag_name("value")) {
                    values.push((
                        required(value, "id")?.to_string(),
                        value.attribute("value").and_then(parse_number),
                    ));
                }
                let Some(address) = control.attribute("address") else {
                    continue;
                };
                let address = parse_number(address)
                    .and_then(|number| u8::try_from(number).ok())
                    .ok_or_else(|| format!("Invalid address in options.xml for {id}: {address}"))?;
                let entry = OptionControl {
                    id,
                    name,
                    kind,
                    values,
                };
                let candidates = result.entry(address).or_default();
                if !candidates.contains(&entry) {
                    candidates.push(entry);
                }
            }
        }
    }
    Ok(result)
}

fn required<'a>(node: Node<'a, '_>, name: &str) -> Result<&'a str, String> {
    node.attribute(name).ok_or_else(|| {
        format!(
            "Missing {name} on {} in options.xml",
            node.tag_name().name()
        )
    })
}

// Match the database's strtol-style decimal, hexadecimal and octal notation.
fn parse_number(value: &str) -> Option<u16> {
    let value = value
        .trim_start()
        .strip_prefix('+')
        .unwrap_or(value.trim_start());
    if let Some(hex) = value
        .strip_prefix("0x")
        .or_else(|| value.strip_prefix("0X"))
    {
        u16::from_str_radix(hex, 16).ok()
    } else if value.starts_with('0') && value.len() > 1 {
        u16::from_str_radix(value, 8).ok()
    } else {
        value.parse().ok()
    }
}

fn matching_values<'a>(
    control: &'a OptionControl,
    advertised: Option<&[u16]>,
) -> Vec<(&'a str, u16)> {
    control
        .values
        .iter()
        .filter_map(|(id, value)| {
            value
                .filter(|value| advertised.is_some_and(|values| values.contains(value)))
                .map(|value| (id.as_str(), value))
        })
        .collect()
}

fn ambiguous_values(values: &[(&str, u16)]) -> bool {
    let ids: BTreeSet<_> = values.iter().map(|(id, _)| id).collect();
    let numbers: BTreeSet<_> = values.iter().map(|(_, number)| number).collect();
    ids.len() != values.len() || numbers.len() != values.len()
}

fn enum_notes(
    xml: &mut String,
    control: &OptionControl,
    advertised: Option<&[u16]>,
    mapped: &[(&str, u16)],
) {
    if let Some(advertised) = advertised {
        let unknown: Vec<_> = advertised
            .iter()
            .filter(|number| !mapped.iter().any(|(_, mapped)| mapped == *number))
            .copied()
            .collect();
        if !unknown.is_empty() {
            comment(
                xml,
                "\t\t",
                &format!(
                    "{}: advertised values without a database mapping: {}.\n\
                     Do not infer their meanings from the numbers alone.",
                    control.id,
                    hex_values(&unknown)
                ),
            );
        }
    }
    if mapped.is_empty() && !control.values.is_empty() {
        let ids: Vec<_> = control.values.iter().map(|(id, _)| id.as_str()).collect();
        comment(
            xml,
            "\t\t",
            &format!(
                "{}: available value IDs: {}.\n\
                 Add <value id=\"VERIFIED_ID\" value=\"VERIFIED_NUMBER\"/> inside\n\
                 the candidate control after confirming the mapping.",
                control.id,
                ids.join(", ")
            ),
        );
    }
}

fn control_xml(control: &OptionControl, code: u8, values: &[(&str, u16)]) -> String {
    let mut xml = format!(
        "\t\t<control id=\"{}\" address=\"0x{code:02X}\"",
        attribute(&control.id)
    );
    if values.is_empty() {
        xml.push_str("/>\n");
    } else {
        xml.push_str(">\n");
        for (id, value) in values {
            writeln!(
                xml,
                "\t\t\t<value id=\"{}\" value=\"0x{value:02X}\"/>",
                attribute(id)
            )
            .unwrap();
        }
        xml.push_str("\t\t</control>\n");
    }
    xml
}

fn normalized_caps(scan: &Scan, codes: &BTreeSet<u8>) -> String {
    let mut output = String::from("(");
    match scan.caps.monitor_type() {
        MonitorType::Lcd => output.push_str("type(lcd)"),
        MonitorType::Crt => output.push_str("type(crt)"),
        MonitorType::Unknown => {}
    }
    output.push_str("vcp(");
    for (index, code) in codes.iter().enumerate() {
        if index > 0 {
            output.push(' ');
        }
        write!(output, "{code:02X}").unwrap();
        if let Some(values) = scan.caps.vcp(*code).and_then(|entry| entry.values()) {
            output.push('(');
            for (index, value) in values.iter().enumerate() {
                if index > 0 {
                    output.push(' ');
                }
                write!(output, "{value:02X}").unwrap();
            }
            output.push(')');
        }
    }
    output.push_str("))");
    output
}

fn hex_values(values: &[u16]) -> String {
    values
        .iter()
        .map(|value| format!("0x{value:02X}"))
        .collect::<Vec<_>>()
        .join(" ")
}

fn xml_char(character: char) -> char {
    match character {
        '\t'
        | '\n'
        | '\r'
        | '\u{20}'..='\u{d7ff}'
        | '\u{e000}'..='\u{fffd}'
        | '\u{10000}'..='\u{10ffff}' => character,
        _ => '\u{fffd}',
    }
}

fn attribute(value: &str) -> String {
    let mut output = String::new();
    for character in value.chars().map(xml_char) {
        match character {
            '&' => output.push_str("&amp;"),
            '<' => output.push_str("&lt;"),
            '>' => output.push_str("&gt;"),
            '"' => output.push_str("&quot;"),
            '\'' => output.push_str("&apos;"),
            '\t' => output.push_str("&#9;"),
            '\n' => output.push_str("&#10;"),
            '\r' => output.push_str("&#13;"),
            character => output.push(character),
        }
    }
    output
}

fn comment(output: &mut String, indent: &str, text: &str) {
    write!(output, "{indent}<!-- ").unwrap();
    let mut previous_dash = false;
    for character in text.chars().map(xml_char) {
        if character == '-' && previous_dash {
            output.push(' ');
        }
        output.push(character);
        previous_dash = character == '-';
    }
    output.push_str(" -->\n");
}

#[cfg(test)]
mod tests {
    use super::*;

    const OPTIONS: &str = include_str!("../fixtures/options.xml");

    fn scan(caps: &str, codes: &[u8]) -> Scan {
        Scan {
            pnp_id: "ABC1234".to_string(),
            name: "Example monitor".to_string(),
            caps: Caps::parse(caps).unwrap(),
            readings: codes
                .iter()
                .map(|code| {
                    (
                        *code,
                        Reading {
                            current: 50,
                            maximum: 100,
                        },
                    )
                })
                .collect(),
        }
    }

    fn active_controls(xml: &str) -> Vec<(String, u8)> {
        Document::parse(xml)
            .unwrap()
            .descendants()
            .filter(|node| node.has_tag_name("control"))
            .map(|node| {
                (
                    node.attribute("id").unwrap().to_string(),
                    parse_number(node.attribute("address").unwrap()).unwrap() as u8,
                )
            })
            .collect()
    }

    #[test]
    fn only_readable_unambiguous_controls_are_enabled() {
        let scan = scan(
            "(type(lcd)vcp(04 10 12 14(05) 1c e1 ff))",
            &[4, 0x10, 0x14, 0x1c, 0xe1],
        );
        let xml = generate(&scan, OPTIONS).unwrap();
        assert_eq!(
            active_controls(&xml),
            vec![("brightness".to_string(), 0x10)]
        );
        assert!(xml.contains("Candidate hue"));
        assert!(xml.contains("Candidate focus"));
        assert!(xml.contains("no successful read"));
        assert!(xml.contains("manufacturer-specific address"));
        assert!(xml.contains("commands require manual verification"));
        assert!(xml.contains("Unknown control: options.xml has no address mapping"));
        assert!(!xml.contains("<include"));
    }

    #[test]
    fn list_values_are_intersected_with_capabilities_without_guessing() {
        let scan = scan("(vcp(60(11 0f 99)))", &[0x60]);
        let xml = generate(&scan, OPTIONS).unwrap();
        let document = Document::parse(&xml).unwrap();
        let values: Vec<_> = document
            .descendants()
            .filter(|node| node.has_tag_name("value"))
            .map(|node| {
                (
                    node.attribute("id").unwrap(),
                    node.attribute("value").unwrap(),
                )
            })
            .collect();
        assert_eq!(values, vec![("hdmi", "0x11"), ("dp", "0x0F")]);
        assert!(xml.contains("without a database mapping: 0x99"));
        assert!(!xml.contains("id=\"dvi\""));
    }

    #[test]
    fn no_enum_choices_are_invented_when_capabilities_omit_values() {
        let xml = generate(&scan("(vcp(60))", &[0x60]), OPTIONS).unwrap();
        assert!(active_controls(&xml).is_empty());
        assert!(xml.contains("available value IDs: hdmi, dp, dvi"));
    }

    #[test]
    fn ambiguous_numeric_labels_remain_candidates() {
        let options = OPTIONS.replace("value=\"0x0f\"", "value=\"0x11\"");
        let xml = generate(&scan("(vcp(60(11)))", &[0x60]), &options).unwrap();
        assert!(active_controls(&xml).is_empty());
        assert!(xml.contains("enum IDs or numbers have more than one possible meaning"));
    }

    #[test]
    fn duplicate_option_ids_at_different_addresses_remain_candidates() {
        let options = OPTIONS.replace("id=\"contrast\"", "id=\"brightness\"");
        let xml = generate(&scan("(vcp(10 12))", &[0x10, 0x12]), &options).unwrap();
        assert!(active_controls(&xml).is_empty());
        assert!(xml.contains("this option ID has several possible addresses"));
    }

    #[test]
    fn candidate_can_be_enabled_by_removing_only_its_comment_wrapper() {
        let xml = generate(&scan("(vcp(10 1c))", &[0x10, 0x1c]), OPTIONS).unwrap();
        let document = Document::parse(&xml).unwrap();
        let candidate = document
            .descendants()
            .find(|node| node.is_comment() && node.text().unwrap().contains("<control id=\"hue\""))
            .unwrap();
        let mut edited = xml.clone();
        edited.replace_range(candidate.range(), candidate.text().unwrap());
        let edited_document = Document::parse(&edited).unwrap();
        let controls = edited_document
            .descendants()
            .find(|node| node.has_tag_name("controls"))
            .unwrap();
        assert!(controls
            .children()
            .filter(|node| node.is_text())
            .all(|node| node.text().unwrap().trim().is_empty()));
        assert_eq!(
            active_controls(&edited),
            [("brightness".to_string(), 0x10), ("hue".to_string(), 0x1c)]
        );
    }

    #[test]
    fn absent_capabilities_do_not_discard_readable_scalar_controls() {
        let scan = scan("", &[0x10, 0x12]);
        let xml = generate(&scan, OPTIONS).unwrap();
        let document = Document::parse(&xml).unwrap();
        let caps = document
            .descendants()
            .find(|node| node.has_tag_name("caps"))
            .unwrap();
        let caps = Caps::parse(caps.attribute("add").unwrap()).unwrap();
        assert_eq!(caps.vcp_codes().collect::<Vec<_>>(), [0x10, 0x12]);
        assert_eq!(active_controls(&xml).len(), 2);
    }

    #[test]
    fn invalid_scalar_ranges_remain_candidates() {
        let mut scan = scan("(vcp(10 12))", &[0x10, 0x12]);
        scan.readings.get_mut(&0x10).unwrap().maximum = 0;
        scan.readings.get_mut(&0x12).unwrap().current = 101;
        assert!(active_controls(&generate(&scan, OPTIONS).unwrap()).is_empty());
    }

    #[test]
    fn monitor_text_and_comments_cannot_break_xml() {
        let mut scan = scan("(vcp(10))", &[0x10]);
        scan.name = "A<&\"'>\t\n\r\u{0}\u{fffe}".to_string();
        scan.pnp_id = "--><injected/>---".to_string();
        let options = OPTIONS.replace("Brightness", "Brightness --&gt;&lt;injected/&gt;");
        let xml = generate(&scan, &options).unwrap();
        let document = Document::parse(&xml).unwrap();
        assert_eq!(
            document.root_element().attribute("name"),
            Some("A<&\"'>\t\n\r\u{fffd}\u{fffd}")
        );
        assert!(!document
            .descendants()
            .any(|node| node.has_tag_name("injected")));
    }

    #[test]
    fn generated_ids_and_values_match_options_vocabulary() {
        let scan = scan("(vcp(10 12 60(11 0f)))", &[0x10, 0x12, 0x60]);
        let xml = generate(&scan, OPTIONS).unwrap();
        let document = Document::parse(&xml).unwrap();
        let options = Document::parse(OPTIONS).unwrap();
        assert_eq!(document.root_element().attribute("init"), Some("standard"));
        assert!(document
            .root_element()
            .children()
            .any(|node| node.has_tag_name("controls")));
        for control in document
            .descendants()
            .filter(|node| node.has_tag_name("control"))
        {
            let option = options
                .descendants()
                .find(|node| {
                    node.has_tag_name("control") && node.attribute("id") == control.attribute("id")
                })
                .unwrap();
            assert!(parse_number(control.attribute("address").unwrap()).unwrap() <= 255);
            for value in control.children().filter(|node| node.has_tag_name("value")) {
                assert!(option.children().any(|node| node.has_tag_name("value")
                    && node.attribute("id") == value.attribute("id")));
                assert!(parse_number(value.attribute("value").unwrap()).is_some());
            }
        }
    }

    #[test]
    fn empty_scan_still_generates_a_loadable_document() {
        let xml = generate(&scan("", &[]), OPTIONS).unwrap();
        let document = Document::parse(&xml).unwrap();
        assert!(document
            .root_element()
            .children()
            .any(|node| node.has_tag_name("controls")));
    }

    #[test]
    fn candidate_addresses_are_unique_and_sorted() {
        assert_eq!(
            candidate_codes(OPTIONS).unwrap(),
            [4, 0x10, 0x12, 0x14, 0x1c, 0x60, 0xe1]
        );
        assert!(candidate_codes("<monitor/>").is_err());
        assert!(candidate_codes(&OPTIONS.replace("dbversion=\"3\"", "dbversion=\"4\"")).is_err());
        assert!(candidate_codes(&OPTIONS.replace("0x10", "0x100")).is_err());
        assert!(candidate_codes(&OPTIONS.replace("type=\"command\"", "type=\"unknown\"")).is_err());
    }

    #[test]
    fn numeric_attributes_follow_database_notation() {
        assert_eq!(parse_number("010"), Some(8));
        assert_eq!(parse_number("+0x10"), Some(16));
        assert_eq!(parse_number(" 65535"), Some(65535));
        for invalid in ["09", "1 ", "-1", "65536", "bad"] {
            assert_eq!(parse_number(invalid), None);
        }
    }
}
